@startuml
scale 750 width
skinparam backgroundColor #AAFFFF
skinparam activity {
  StartColor red
  BarColor SaddleBrown
  EndColor Silver
  BackgroundColor Peru
  BackgroundColor<< Begin >> Olive
  BorderColor Peru

}

"Source 1" --> "Some activity"
--> (*)

"Source 2" --> "Some other activity"
--> (*)

@enduml